
import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * form que representa a una ventana
 * @author Daniel López Avilés
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new ventana VentanaPrincipal
     */
    //Array para añadir partidos
    ArrayList<String>array=new ArrayList<>();
    //Array para añadir partidos con sus resultados
    ArrayList<String>array2=new ArrayList<>();
    /**
     * Constructor por defecto de la ventana
     */
    public VentanaPrincipal() {
        initComponents();
    }
    /**
     * Metodo para agregar partidos desde la otra ventana
     * @param texto Partido para añadir
     */
    public void agregarPartido(String texto)
    {
        DefaultListModel a = new DefaultListModel();
        
        array.add(texto);
        for (int i = 0; i <array.size(); i++) {
            a.addElement(array.get(i));
        }
        jlLista1.setModel(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPanel1 = new javax.swing.JPanel();
        lQuiniela = new javax.swing.JLabel();
        pPanel2 = new javax.swing.JPanel();
        spScroll1 = new javax.swing.JScrollPane();
        jlLista1 = new javax.swing.JList<>();
        pPanel3 = new javax.swing.JPanel();
        pPanel5 = new javax.swing.JPanel();
        bNuevo = new javax.swing.JButton();
        pPanel6 = new javax.swing.JPanel();
        bEliminar = new javax.swing.JButton();
        pPanel7 = new javax.swing.JPanel();
        bRealizar = new javax.swing.JButton();
        pPanel8 = new javax.swing.JPanel();
        bResetear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlLista2 = new javax.swing.JList<>();
        pPanel4 = new javax.swing.JPanel();
        lPartidos = new javax.swing.JLabel();
        lResultados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lQuiniela.setBackground(new java.awt.Color(255, 255, 255));
        lQuiniela.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lQuiniela.setForeground(new java.awt.Color(255, 0, 0));
        lQuiniela.setText("Quiniela");
        pPanel1.add(lQuiniela);

        getContentPane().add(pPanel1, java.awt.BorderLayout.NORTH);

        pPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pPanel2.setToolTipText("");
        pPanel2.setLayout(new java.awt.GridLayout(1, 3));

        spScroll1.setViewportView(jlLista1);

        pPanel2.add(spScroll1);

        pPanel3.setLayout(new java.awt.GridLayout(6, 1));

        bNuevo.setText("Nuevo");
        bNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoActionPerformed(evt);
            }
        });
        pPanel5.add(bNuevo);

        pPanel3.add(pPanel5);

        bEliminar.setText("Eliminar");
        bEliminar.setMaximumSize(new java.awt.Dimension(20, 23));
        bEliminar.setMinimumSize(new java.awt.Dimension(20, 23));
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });
        pPanel6.add(bEliminar);

        pPanel3.add(pPanel6);

        bRealizar.setText("Realizar Quiniela");
        bRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRealizarActionPerformed(evt);
            }
        });
        pPanel7.add(bRealizar);

        pPanel3.add(pPanel7);

        bResetear.setText("Resetear");
        bResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetearActionPerformed(evt);
            }
        });
        pPanel8.add(bResetear);

        pPanel3.add(pPanel8);

        pPanel2.add(pPanel3);

        jScrollPane1.setViewportView(jlLista2);

        pPanel2.add(jScrollPane1);

        getContentPane().add(pPanel2, java.awt.BorderLayout.SOUTH);

        pPanel4.setLayout(new java.awt.BorderLayout());

        lPartidos.setText("Partidos");
        pPanel4.add(lPartidos, java.awt.BorderLayout.CENTER);

        lResultados.setText("Resultados");
        pPanel4.add(lResultados, java.awt.BorderLayout.EAST);

        getContentPane().add(pPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Metodo que llama a la ventana2 y la muestra
 * @param evt Pulsar el boton Nuevo
 */
    private void bNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoActionPerformed
        Ventana2 ventana2=new Ventana2(this);
        ventana2.setVisible(true);
    }//GEN-LAST:event_bNuevoActionPerformed
/**
 * Metodo eliminar, que elimina un componente de la lista de partidos
 * @param evt Pulsar boton eliminar
 */
    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        int numero=jlLista1.getSelectedIndex();
        array.remove(numero);
        DefaultListModel a = new DefaultListModel();
        
        for (int i = 0; i <array.size(); i++) {
            a.addElement(array.get(i));
        }
        jlLista1.setModel(a);
    }//GEN-LAST:event_bEliminarActionPerformed
/**
 * Método para borrar todos los partidos y todos los resultados
 * @param evt Pulsar boton resetear
 */
    private void bResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetearActionPerformed
        DefaultListModel a = new DefaultListModel();
        jlLista1.setModel(a);
        jlLista2.setModel(a);
    }//GEN-LAST:event_bResetearActionPerformed
/**
 * Método que rellena la quiniela, y lo muestra en la lista de resultados
 * @param evt Pulsar boton realizarquiniela
 */
    private void bRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizarActionPerformed
        Random aleatorio=new Random();
        for (int i = 0; i <array.size(); i++) {
            int numero=aleatorio.nextInt(3);
            String cadena=array.get(i);
            if(numero==0)
            {
                cadena=cadena+"-> X";
                array2.add(cadena);
            }
            else
            {
                cadena=cadena+"-> "+numero;
                array2.add(cadena);
            }
        }
        DefaultListModel a = new DefaultListModel();
        for (int i = 0; i <array2.size(); i++) {
            a.addElement(array2.get(i));
        }
        jlLista2.setModel(a);
        
    }//GEN-LAST:event_bRealizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bNuevo;
    private javax.swing.JButton bRealizar;
    private javax.swing.JButton bResetear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlLista1;
    private javax.swing.JList<String> jlLista2;
    private javax.swing.JLabel lPartidos;
    private javax.swing.JLabel lQuiniela;
    private javax.swing.JLabel lResultados;
    private javax.swing.JPanel pPanel1;
    private javax.swing.JPanel pPanel2;
    private javax.swing.JPanel pPanel3;
    private javax.swing.JPanel pPanel4;
    private javax.swing.JPanel pPanel5;
    private javax.swing.JPanel pPanel6;
    private javax.swing.JPanel pPanel7;
    private javax.swing.JPanel pPanel8;
    private javax.swing.JScrollPane spScroll1;
    // End of variables declaration//GEN-END:variables
}
