/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * form que representa a una ventana
 * @author Daniel López Avilés
 */
public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new ventana Ventana2
     */
    private VentanaPrincipal ventana2;
    /**
     * Constructor por parametros de la ventana
     * @param ventana2 
     */
    public Ventana2(VentanaPrincipal ventana2) {
        initComponents();
        this.ventana2=ventana2;
    }
    /**
     * Constructor por defecto de la ventana
     */
    public Ventana2()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPanel1 = new javax.swing.JPanel();
        lPartido = new javax.swing.JLabel();
        tfArea1 = new javax.swing.JTextField();
        bAceptar = new javax.swing.JButton();
        pPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(379, 44));
        setResizable(false);

        pPanel1.setLayout(new javax.swing.BoxLayout(pPanel1, javax.swing.BoxLayout.LINE_AXIS));

        lPartido.setText("Partido");
        pPanel1.add(lPartido);

        tfArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfArea1ActionPerformed(evt);
            }
        });
        pPanel1.add(tfArea1);

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });
        pPanel1.add(bAceptar);

        getContentPane().add(pPanel1, java.awt.BorderLayout.NORTH);

        pPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Advertencia: Ventana de subprograma");
        pPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pPanel2, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfArea1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfArea1ActionPerformed
    /**
     * Método para agregar partidos en la ventana principal
     * @param evt Pulsar boton agregar
     */
    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        String texto = tfArea1.getText();
        ventana2.agregarPartido(texto);
    }//GEN-LAST:event_bAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lPartido;
    private javax.swing.JPanel pPanel1;
    private javax.swing.JPanel pPanel2;
    private javax.swing.JTextField tfArea1;
    // End of variables declaration//GEN-END:variables
}
